package com.statushub.india.ui.theme

import androidx.compose.ui.graphics.Color

val md_theme_dark_primary = Color(0xFF4ae176)
val md_theme_dark_onPrimary = Color(0xFF003915)
val md_theme_dark_primaryContainer = Color(0xFF001d07)
val md_theme_dark_onPrimaryContainer = Color(0xFF009542)
val md_theme_dark_secondary = Color(0xFFffb95f)
val md_theme_dark_onSecondary = Color(0xFF472a00)
val md_theme_dark_secondaryContainer = Color(0xFFee9800)
val md_theme_dark_onSecondaryContainer = Color(0xFF5b3800)
val md_theme_dark_tertiary = Color(0xFF7bd0ff)
val md_theme_dark_onTertiary = Color(0xFF00354a)
val md_theme_dark_tertiaryContainer = Color(0xFF001a27)
val md_theme_dark_onTertiaryContainer = Color(0xFF008abb)
val md_theme_dark_error = Color(0xFFffb4ab)
val md_theme_dark_onError = Color(0xFF690005)
val md_theme_dark_errorContainer = Color(0xFF93000a)
val md_theme_dark_onErrorContainer = Color(0xFFffdad6)
val md_theme_dark_background = Color(0xFF0b1326)
val md_theme_dark_onBackground = Color(0xFFdae2fd)
val md_theme_dark_surface = Color(0xFF0b1326)
val md_theme_dark_onSurface = Color(0xFFdae2fd)
val md_theme_dark_surfaceVariant = Color(0xFF2d3449)
val md_theme_dark_onSurfaceVariant = Color(0xFFc6c6cd)
val md_theme_dark_outline = Color(0xFF909097)
val md_theme_dark_inverseOnSurface = Color(0xFF283044)
val md_theme_dark_inverseSurface = Color(0xFFdae2fd)
val md_theme_dark_inversePrimary = Color(0xFF006e2f)